# Generated by Django 4.1.1 on 2022-09-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTimeCode',
            fields=[
                ('time_code', models.IntegerField(primary_key=True, serialize=False)),
                ('time_code_description', models.TextField(max_length=100)),
            ],
        ),
    ]
