# Generated by Django 4.1.1 on 2022-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tbltimecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTypes',
            fields=[
                ('type_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
    ]
