# Generated by Django 4.1.1 on 2022-09-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tbltypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTimeSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('fye', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tblemployee')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tblprovider')),
                ('time_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbltimecode')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbltypes')),
            ],
        ),
    ]
