# Generated by Django 4.1.1 on 2022-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tbltimesheet_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltimesheet',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
