# Generated by Django 4.1.1 on 2022-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tbltimesheet_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltimecode',
            name='time_code_description',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='tbltimesheet',
            name='fye',
            field=models.DateField(blank=True, null=True),
        ),
    ]
