# Generated by Django 4.1.1 on 2022-10-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_tbltimesheet_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbltimecode",
            name="time_code_description",
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name="tbltimesheet",
            name="fye",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TblToDoList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("fye", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.tblemployee",
                    ),
                ),
                (
                    "provider_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.tblprovider",
                    ),
                ),
                (
                    "time_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.tbltimecode",
                    ),
                ),
            ],
        ),
    ]
