# Generated by Django 4.1.1 on 2022-10-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tbltimecode_time_code_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblToDoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tblemployee')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tblprovider')),
                ('time_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbltimecode')),
            ],
        ),
    ]
