# Generated by Django 4.1.1 on 2022-10-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tbltodolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltodolist',
            name='fye',
            field=models.DateField(blank=True, null=True),
        ),
    ]
