# Generated by Django 4.1.1 on 2022-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tbltodolist_fye'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltodolist',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
